name = "mail-worker"
main = "src/index.ts"
compatibility_date = "2026-08-13"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1

# Uncomment if your API token is not scoped to exactly one account:
# account_id = "your-account-id"

[[send_email]]
name = "EMAIL"
remote = true
